#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

protected_branch='main'
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ $protected_branch = $current_branch ]
then
    exit 1
else
    exit 0 # push will execute
fi